In [1]:
# https://www.kaggle.com/shayanfazeli/heartbeat   # data set 

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt # plotting
import os
import sklearn
from keras.models import Sequential
from keras.layers import Flatten, Dense, Dropout, BatchNormalization, AveragePooling2D
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import scipy
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import cross_validate

Using TensorFlow backend.


In [2]:
# reading csv file  

test=pd.read_csv("mitbih_test.csv",header=None) 
train=pd.read_csv("mitbih_train.csv",header=None) 
#Classes: ['N': 0, 'S': 1, 'V': 2, 'F': 3, 'Q': 4]
# N- normal, S-supraventricular, V-ventricular, F-fusion, Q- unknown



In [4]:
print("Type\tCount")
print((train[187]).value_counts())

print("train shape : ",train.shape)
print("test shape : ",test.shape)


Type	Count
0.0    72471
4.0     6431
2.0     5788
1.0     2223
3.0      641
Name: 187, dtype: int64
train shape :  (87554, 188)
test shape :  (21892, 188)


In [5]:
print('Count of all classes in training dataset')
print("Type\tCount")
print((train[187]).value_counts())

print('*************************************')

print('Count of all classes in test dataset')
print("Type\tCount")
print((test[187]).value_counts())

Count of all classes in training dataset
Type	Count
0.0    72471
4.0     6431
2.0     5788
1.0     2223
3.0      641
Name: 187, dtype: int64
*************************************
Count of all classes in test dataset
Type	Count
0.0    18118
4.0     1608
2.0     1448
1.0      556
3.0      162
Name: 187, dtype: int64


In [6]:
print("train shape : ",train.shape)
print("test shape : ",test.shape)

feature_train=train.iloc[:,0:187] 
print("feature_train shape : ",feature_train.shape)

labels_train=train.iloc[:,187] 
print("labels_train shape : ",labels_train.shape)

feature_test=test.iloc[:,0:187] 
print("feature_test shape : ",feature_test.shape)

labels_test=test.iloc[:,187] 
print("labels_test shape : ",labels_test.shape)
      


train shape :  (87554, 188)
test shape :  (21892, 188)
feature_train shape :  (87554, 187)
labels_train shape :  (87554,)
feature_test shape :  (21892, 187)
labels_test shape :  (21892,)


In [7]:
from sklearn.preprocessing import StandardScaler
standardized_training_data=StandardScaler().fit_transform(feature_train)
feature_train=standardized_training_data

standardized_test_data=StandardScaler().fit_transform(feature_test)
feature_test=standardized_test_data

In [8]:
from keras.utils import np_utils 
from keras.datasets import mnist 
import seaborn as sns
from keras.initializers import RandomNormal
#from keras.initializers import glorot_normal

In [9]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import time
def plt_dynamic(x, vy, ty, ax, colors=['b']):
    ax.plot(x, vy, 'b', label="Validation Loss")
    ax.plot(x, ty, 'r', label="Train Loss")
    plt.legend()
    plt.grid()
    fig.canvas.draw()

In [10]:
import numpy as np
from keras.utils import np_utils 
import seaborn as sns
from keras.initializers import RandomNormal
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
from keras.preprocessing import sequence
# fixed random seed for reproducibility
np.random.seed(7)


In [11]:
x_train1=feature_train
x_test1=feature_test
y_train1=labels_train
y_test1=labels_test

In [12]:
x_train1=x_train1.reshape(x_train1.shape[0],1,x_train1.shape[1])
x_test1=x_test1.reshape(x_test1.shape[0],1,x_test1.shape[1])


In [13]:
# here we are having a class number for each image
print("Class label of first image :",y_train1[83456])


Y_train = np_utils.to_categorical(y_train1)
print("After converting the output into a vector : ",Y_train[83456])

Y_test = np_utils.to_categorical(y_test1)

Class label of first image : 4.0
After converting the output into a vector :  [0. 0. 0. 0. 1.]


In [14]:
print("feature_train",x_train1.shape)
print("Y_train",Y_train.shape)
print("feature_test",x_test1.shape)
print("Y_test",Y_test.shape)

feature_train (87554, 1, 187)
Y_train (87554, 5)
feature_test (21892, 1, 187)
Y_test (21892, 5)


In [15]:
output_dim = 5
input_dim = feature_train.shape[1]

batch_size = 512
nb_epoch = 100

model_lstm =Sequential()
#model_lstm.add(Embedding)
model_lstm.add(LSTM(100))
model_lstm.add(Dense(output_dim, input_dim=input_dim, activation='softmax'))
model_lstm.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])



In [16]:

model_lstm.fit(x_train1, Y_train, epochs=100,batch_size=512)


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/100
87554/87554 [==============================] - 4s 45us/step - loss: 0.1402 - accuracy: 0.9532
Epoch 2/100
87554/87554 [==============================] - 3s 37us/step - loss: 0.0664 - accuracy: 0.9810
Epoch 3/100
87554/87554 [==============================] - 3s 35us/step - loss: 0.0537 - accuracy: 0.9845
Epoch 4/100
87554/87554 [==============================] - 3s 38us/step - loss: 0.0456 - accuracy: 0.9865
Epoch 5/100
87554/87554 [==============================] - 3s 33us/step - loss: 0.0403 - accuracy: 0.9880
Epoch 6/100
87554/87554 [==============================] - 3s 30us/step - loss: 0.0363 - accuracy: 0.9891
Epoch 7/100
87554/87554 [==============================] - 3s 30us/step - loss: 0.0345 - accuracy: 0.9895
Epoch 8/100
87554/87554 [==============================] - 3s 30us/step - loss: 0.0363 - accuracy: 0.9890
Epoch 9/100
87554/87554 [==============================] 

In [17]:
predictions=model_lstm.predict(x_test1)

In [18]:
print(classification_report(Y_test.argmax(axis=1), predictions.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     18118
           1       0.86      0.73      0.79       556
           2       0.95      0.93      0.94      1448
           3       0.80      0.73      0.77       162
           4       0.99      0.97      0.98      1608

    accuracy                           0.98     21892
   macro avg       0.92      0.87      0.89     21892
weighted avg       0.98      0.98      0.98     21892



In [19]:
print(predictions)
a=predictions.argmax(axis=1)     # 0 is row and 1 is column
print(a)

#create new df 
a = pd.DataFrame({'col':a})

print("Type\tCount")
print((a['col']).value_counts())

[[9.9999976e-01 2.0034449e-07 6.7784994e-10 4.2476191e-09 2.0487097e-12]
 [9.9935335e-01 6.4302690e-04 3.9515780e-07 1.1698351e-06 2.0317318e-06]
 [9.9960178e-01 3.9787657e-04 3.2744179e-08 1.9177236e-07 7.1629628e-08]
 ...
 [7.4875976e-07 1.3920576e-06 1.0132168e-06 6.1560850e-06 9.9999070e-01]
 [2.4811877e-11 6.7677461e-12 2.3957147e-12 7.6608494e-12 1.0000000e+00]
 [5.8706806e-10 1.4574129e-12 9.3095043e-10 2.9991423e-10 1.0000000e+00]]
[0 0 0 ... 4 4 4]
Type	Count
0    18260
4     1587
2     1422
1      474
3      149
Name: col, dtype: int64


In [3]:
 #             precision    recall  f1-score   support

 #          0       0.99      0.99      0.99     18118
 #          1       0.86      0.73      0.79       556
 #          2       0.95      0.93      0.94      1448
 #          3       0.80      0.73      0.77       162
  #         4       0.99      0.97      0.98      1608

#    accuracy                           0.98     21892
#   macro avg       0.92      0.87      0.89     21892
#weighted avg       0.98      0.98      0.98     21892
